spring:
  application:
    name: patient-service
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      file: compose.yml
  datasource:
    url: jdbc:h2:mem:patientdb
    username: patient
    password: secret
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  h2:
    console:
      path: /patient-console
      enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      retries: 3
      properties:
        linger.ms: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 4001
