spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      auto-offset-reset: earliest
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:analytics-service}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
        max.poll.records: 100
        fetch.min.bytes: 1
        fetch.max.wait.ms: 500
        heartbeat.interval.ms: 3000
        session.timeout.ms: 10000

server:
  port: 4003
